### ISSUE TITLE
Error when converting llama-3.2-11b-vision-instruct

### ISSUE THREAD

**Issue by AlexMisiulia** [OpenNMT/CTranslate2#1794]
When I tried to convert `llama-3.2-11b-vision-instruct` downloaded from hugging face using this command:
```bash
ct2-transformers-converter --model /root/llama-3.2-11b-vision-instruct/ --output_dir /root/ct2_manually_converted
```

I got the error:
```
ValueError: No conversion is registered for the model configuration MllamaConfig (supported configurations are: BartConfig, BertConfig, BloomConfig, CodeGenConfig, DistilBertConfig, FalconConfig, GPT2Config, GPTBigCodeConfig, GPTJConfig, GPTNeoXConfig, Gemma2Config, GemmaConfig, LlamaConfig, M2M100Config, MBartConfig, MPTConfig, MT5Config, MarianConfig, MistralConfig, MixFormerSequentialConfig, OPTConfig, PegasusConfig, Phi3Config, PhiConfig, RWConfig, T5Config, Wav2Vec2Config, WhisperConfig, XLMRobertaConfig)
```

pyproject.toml excerpt is:
```toml
[tool.poetry.dependencies]
python = "^3.11"
transformers = {extras = ["torch"], version = "^4.45.1"}
ctranslate2 = "^4.4.0"
```

Do you have plans to implement this converter?
