### ISSUE TITLE
Totally different translation from inference results

### ISSUE THREAD

**Issue by ptamas88** [OpenNMT/CTranslate2#547]
Hello,
I have trained a model with the following params:
`onmt-main --model_type Transformer --config run_tokenized/data.yml --auto_config train --with_eval`
where the config file only contains the corpus paths, and the target directory, nothing special.

After some steps I stopped training and tried to get some test results with this sample code:
`onmt-main --config run_tokenized/data.yml --auto_config infer --features_file test_in_tok.txt`
The input file is tokenized the same way as the training files.

The results seemed acceptable so I exported the model using again the sample code:
`onmt-main --config run_tokenized/data.yml --auto_config export --output_dir exported_model --format ctranslate2`
The export is done everything seems fine so far.

Then used the following python code:
```
import ctranslate2
tokens = [[...]]
translator = ctranslate2.Translator(model_folder_path, device='cuda', device_index=1)
output_tokens = translator.translate_batch(tokens, return_scores=True, return_attention=True)
```
This time the output tokens contains totally different results compared to the one which I got from inference.
By saying totally different it means not just slight differences in one or two tokens but semantically wrong translation with different tokens or not any tokens at all.

Can you help please what mistake have I made?

**Comment by guillaumekln** [comment]
Hi,

Can you show an example? Please post the input and output when using OpenNMT-tf and CTranslate2.

**Comment by ptamas88** [comment]
hello @guillaumekln,
Thanks for the reply, this is an english-hungarian translator, so the output may be weird for you but I think the difference between the outputs is understandable without knowing the hungarian language.
Inputs
```
example1: 'Parliament is working on a proposal that aims to ensure minimum wages provide for decent living in the EU.'
example2: 'The proposal takes into account national competences and social partners’ contractual freedom and does not set the level of minimum wages.'
example3: 'This dog helped him watch the sheep.'
example4: 'The cat would like to eat the mouse.'
example5: 'In that small house, there were few secrets.'
example6: 'The blue house is open.'
example7: 'The dog crossed the street.'
```
Output - OpenNMT-tf
```
example1: 'A Parlament olyan javaslaton dolgozik , amelynek célja annak biztosítása , hogy a minimálbérek tisztességes megélhetést biztosítsanak az EU - ban .'
example2: 'A javaslat figyelembe veszi a nemzeti kompetenciákat és a szociális partnereket , a szerződéses szabadságot , és nem határozza meg a minimálbér szintjét .'
example3: 'Ez a dogma segített neki a juhok megfigyelésében .'
example4: 'A macska szeretnék egér .'
example5: 'Ebben a kis házban alig voltak titkok .'
example6: 'A kék ház nyitva áll .'
example7: 'A kutya keresztezi az utcát .'
```

Output - cTranslate2
```
example1: 'próbálnak meg úgy szavazni , hogy a minimálbérek valóban megfelelő és megélhetést biztosítsanak az Európai Unióban . '
example2: 'próbálnak meg úgy szavazni , hogy a nemzeti hatáskörök és a szociális partnerek kölcsönösen alkalmazzák a szerződési szabadságot , és nem határozza meg a minimálbér szintjét . '
example3: 'idén ugyan . '
example4: '. '
example5: 'általában viselkedni . '
example6: '. '
example7: 'általában . '
```

**Comment by guillaumekln** [comment]
The inputs are not tokenized. Where do you apply the tokenization? Did you make sure you applied the same tokenization before translating with CTranslate2?

**Comment by ptamas88** [comment]
yeah, sorry, i posted the detokenized version of either the input and the output for readability.
The tokenization is done with Cased BERT-Large's vocabulary file and tokenizer script, this is why you see some tokens starts with ## in the output
here is one of the examples with the tokenized version:
input:
`['The', 'dog', 'crossed', 'the', 'street', '.']`
output - onmt-tf:
['A', 'kutya', 'kereszt', '##ezi', 'az', 'utc', '##át', '.']
output - ctranslate2
['általában', '.']
I am splitting the output at the first '[CLS]' token but here is a longer output:
['általában', '.', '[CLS]', '.', '[CLS]', '.', '[CLS]', '.', '[CLS]', '.', '[CLS]', ...]

**Comment by guillaumekln** [comment]
For completeness, can you post the content of your configuration file `run_tokenized/data.yml`?

**Comment by ptamas88** [comment]
sure, but it is very basic, this is the first experiment so i haven't finetuned any settings
```
#data.yml
model_dir: /storage/Neural-Machine-Translation/Europarl/run_tokenized/

data:
  # Data configuration (training and evaluation files, vocabularies, alignments, etc.)
  train_features_file: /storage/Neural-Machine-Translation/Europarl/berttokenized_train_620000.en
  train_labels_file: /storage/Neural-Machine-Translation/Europarl/berttokenized_train_620000.hu
  eval_features_file: /storage/Neural-Machine-Translation/Europarl/berttokenized_eval_5178.en
  eval_labels_file: /storage/Neural-Machine-Translation/Europarl/berttokenized_eval_5178.hu
  source_vocabulary: /storage/Neural-Machine-Translation/tokenizers/cased_bert_large-vocab.txt
  target_vocabulary: /storage/Neural-Machine-Translation/tokenizers/hubert-vocab.txt
```
